### ISSUE TITLE
toTrytes() cannot revert all values from fromTrytes()

### ISSUE THREAD

**Issue by vbakke** [iotaledger/iota.js#137]
I believe there is a bug in asciiToTrytes.js, toTrytes(). Try the following:
```javascript
var IOTA = require('iota.lib.js');

var iota = new IOTA();
var trytes = 'TCSR';
var binary = iota.utils.fromTrytes(trytes);   // Convert from trytes
var attempt = iota.utils.toTrytes(binary);    // Convert back to trytes
console.log(trytes, binary, attempt);         // Outputs: TCSR eǹ null
```

TC converts to "ascii" 101 'e'.
SR converts to "ascii" 505 'ǹ'.

As you see, SR is not a 7-bit, nor 8-bit, ascii character. But JS uses UTF-16 for strings, and holds two bytes per character. Therefore this works as a charm.

But converting it back, yields null, because of:
```
// If not recognizable ASCII character, return null
if (asciiValue > 255) {
```

which should be:
```
// If bigger than one tryte, return null 
if (asciiValue >= 27*27) {
```

With this minor fix, the tryte TCSR can be converted back an forth.

(I found this bug, trying to decode an IOTA address that started with CU, i.e. 570, \u023a or Ⱥ, depending on how you like formatting the value.  Therefore I think the scope is valid, and not outside scope. Even though the toTrytes(), I assume, is mainly used on 8-bit bytes.)

**Comment by vbakke** [comment]
Not sure if the solution is quite this simple.  Tryte <-> byte conversion will never match both ways.

I've started a new discussion in: [vbakke/trytes](https://github.com/vbakke/trytes)

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
