### ISSUE TITLE
utils.inputValidator.isUri does not recognize tcp://[::ffff:<IPv4>]:<port> as valid.

### ISSUE THREAD

**Issue by romansemko** [iotaledger/iota.js#156]
Wrapping IPv4 format into IPV6 is legit. The Uri validator does not recognise it.

**Comment by henriklaxhuber** [comment]
Note that isUri never matches the http protocol but only uris in the form of `tcp://` or `udp://`. Nonetheless, it does not match the described scenario even when given a suitable protocol.

I believe a fix would be to change the `getInside` regex to `/^(udp|tcp):\/\/(:ffff:)?([\[][^\]\.]*[\]]|[^\[\]:]*)[:]{0,1}([0-9]{1,}$|$)/i`, although I have not confirmed this - those regexes are lengthy and somewhat difficult to understand without further investigation.

**Comment by romansemko** [comment]
Sorry, my bad. I have adjusted the protocol in the ticket description.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
