### ISSUE TITLE
Error: Invalid Response:  makerequest.js

### ISSUE THREAD

**Issue by deepanigi** [iotaledger/iota.js#176]
I am using IOTA lib in angular app. I have mentioned the error i am facing.

```
import IOTA from 'iota.lib.js';
    var iota = new IOTA({
    'host': 'https://potato.iotasalad.org',
    'port': 14265
    });
console.log(iota);
console.log(iota.version);

iota.api.getNodeInfo(function(error, success) {
if (error) {
    console.log(error);
} else {
    console.log(success);
}
});
    };
```
Error in console 

> Failed to load https://potato.iotasalad.org:14265/: Response for preflight is invalid (redirect)
> home.component.ts:67 Error: Invalid Response: 
>     at Object.invalidResponse (requestErrors.js:5)
>     at makeRequest.webpackJsonp.../../../../iota.lib.js/lib/utils/makeRequest.js.makeRequest.prepareResult (makeRequest.js:285)
>     at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (makeRequest.js:71)
>     at XMLHttpRequest.wrapFn (zone.js:1166)
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.es5.js:3881)
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:188)
>     at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
>     at invokeTask (zone.js:1517)
> client?ffdb:120 [WDS] Warnings while compiling.
> warnings @ client?ffdb:120
> sock.onmessage @ socket.js:37
> webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
> (anonymous) @ main.js:274
> webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
> webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
> WebSocketTransport.ws.onmessage @ websocket.js:35
> wrapFn @ zone.js:1166
> webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
> webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:188
> webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
> invokeTask @ zone.js:1517
> globalZoneAwareCallback @ zone.js:1543
> client?ffdb:126 ./node_modules/iota.lib.js/lib/utils/makeRequest.js
> 10:16-46 Critical dependency: the request of a dependency is an expression

![iotaerror](https://user-images.githubusercontent.com/31543067/36073434-b11ea35e-0f30-11e8-8023-8ca11eb5d610.JPG)

**Comment by rajivshah3** [comment]
Your situation might be similar to the one in this thread: https://discuss.elastic.co/t/response-for-preflight-is-invalid-redirect-with-angularjs-and-elasticsearch/88092

Does it happen in incognito mode with all extensions disabled?

**Comment by deepanigi** [comment]
@rajivshah3 Thanks for your response.  i am still facing the same issue in incognito as well.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
