### ISSUE TITLE
proxy compatibility

### ISSUE THREAD

**Issue by dsir-minute** [iotaledger/iota.js#178]
Hi,
when I run a nodejs app , which uses this Library , from behind a proxy
then the requests get rejected;

This is a know issue for nodejs in general and the solution shall be to use a proxyagent for helping.

Has anyone found the same issue ?
How to simply deal with it ? (I had a look at examples in https://www.npmjs.com/package/proxy-agent, but canot find how to apply it)
thanks

```
nodeInfo err:Error: Invalid Response: Error: getaddrinfo ENOTFOUND nodes.iota.fm nodes.iota.fm:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by Veqetazxy** [comment]
I must copy here, i did post in the wallet repo <.< 
RE:
Is there a proxy support, or it is planned for the coming future?
At my company its a pain with our proxy .. and cant solve this with cntlm, in this case.
Worked some stuff on Hackathons in Stuttgart and Berlin with node.js.
If someone have a workaround for that I'am kind about every hint :)

Lets Push this :)
