### ISSUE TITLE
hmacKey option for prepareTransfer does not get included in signatureFragment

### ISSUE THREAD

**Issue by obany** [iotaledger/iota.js#182]
Not sure if this part of the API is actually used anywhere as it is not documented. If you add an hmacKey in the options to prepareTransfer it successfully allocates the space in the signatureFragment to store it, but doesn't actually put it in there.

The addHMAC method currently looks like this

https://github.com/iotaledger/iota.lib.js/blob/a1b2e9e05d7cab3ef394900e5ca75fb46464e608/lib/crypto/hmac/hmac.js#L9-L24

But because the curl methods are called without offset and length parameters the hmacTrytes are always blank (internally the curl state ends up with lots of 'undefined' elements in it)

To fix this just change the addHMAC method to be:

```
            curl.absorb(key, 0, key.length);
            curl.absorb(bundleHashTrits, 0, bundleHashTrits.length);
            curl.squeeze(hmac, 0, hmac.length);
```

Fix in this PR https://github.com/iotaledger/iota.lib.js/pull/184

**Comment by chrisdukakis** [comment]
closing, `v0.5.0` includes the fix
