### ISSUE TITLE
getAccountData return incorrect index for inputs

### ISSUE THREAD

**Issue by obany** [iotaledger/iota.js#183]
When the getAccountData creates its inputs data, it does not take into account the startIndex handed to the method.

https://github.com/iotaledger/iota.lib.js/blob/a1b2e9e05d7cab3ef394900e5ca75fb46464e608/lib/api/api.js#L1805-L1810

The getInputs method which is similar handles this correctly.

https://github.com/iotaledger/iota.lib.js/blob/a1b2e9e05d7cab3ef394900e5ca75fb46464e608/lib/api/api.js#L1006-L1010

**Comment by chrisdukakis** [comment]
closing, `v0.5.0` includes the fix
