### ISSUE TITLE
`iota.utils.toTrytes` and `fromTrytes` should use vbakke/trytes for better compression

### ISSUE THREAD

**Issue by zocoi** [iotaledger/iota.js#186]
Here's the link to the repo:
https://github.com/vbakke/trytes
and the code https://github.com/vbakke/trytes/blob/master/src/trytes.js#L182

In the author's words:

> The current implementation encodes an 8 bit byte, into a 6 trit tryte.
> In other words, a 0-255 value, into a 0-728 value (written as to tryte3 chars).
> 
> A 100 char ANSI message, end up as 200 tryte chars.
> 
> The best fit I've found (and is also a small and handy one), is fitting every 3 bit (0-7) into 2 trits (0-8). (Or 6 bits into 4 trits, as @paulshandy mentioned above.)
> 
> Then a 100 char ANSI message will end up as 134 tryte chars. (Plus some padding or length codes suggested.)

It would help to embed more data in a transaction's message or tag

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
