### ISSUE TITLE
API calls never timeouts when given invalid url

### ISSUE THREAD

**Issue by yet-another-account** [iotaledger/iota.js#189]
API should time out after a given time.

To reproduce:

    let iota = new IOTA({
        provider: 'http://example.com:14265',
    });
    iota.api.getNodeInfo((err, res) => { console.log(err ? err : res); }); // hangs forever

**Comment by eukaryote31** [comment]
Adding `request.timeout = 10000` or something like that [here](https://github.com/iotaledger/iota.lib.js/blob/e60c728c836cb37f3d6fb8b0eff522d08b745caa/lib/utils/makeRequest.js#L44) would fix it, albeit inelegantly. If there's a way to pass a timeout parameter from api call, and then have a global default, that would be best.

**Comment by chrisdukakis** [comment]
#192 addresses this and can be merged to master.
In v1.0.0, which which works fetch, we'll probably have to implement `AbortController` and `AbortSignal`. Those should be enabled by passing a `settings.timeout` option right here:
https://github.com/chrisdukakis/iota.lib.js/blob/next/lib/utils/provider.ts#L29

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
