### ISSUE TITLE
Feature request - add support for more then 1 CPU

### ISSUE THREAD

**Issue by avihai-developer** [iotaledger/iota.js#197]
Hi can you please add support for more then 1 CPU use?
Alot of the lib API request required alot of cpu processing for now this lib not really useable for mobile users and low powered IOT devices.

This problem could be solved by using web workers

**Comment by chrisdukakis** [comment]
@avihai-developer I'm not sure how this could abstracted as a library component. Could you think of a suitable spec to abstract this functionality, so that it can be used both in browser and node? Perhaps solution requires specialized build process too.

**Comment by avihai-developer** [comment]
I think workerpool will be the best choice
https://www.npmjs.com/package/workerpool

**Comment by chrisdukakis** [comment]
Thank you! Will look at it come back to this issue in due time. Other performance improvements are being considered too, such us using wasm and C bindings in node.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
