### ISSUE TITLE
The .words_to_trits() fails reverting the result from .trits_to_words() 

### ISSUE THREAD

**Issue by vbakke** [iotaledger/iota.js#216]
### Bug description
Converting a tryte seed to bytes, and back failes, using iota.lib.js/lib/crypto/converter.

### Errors
Paste any errors that you see.
```javascript
const Converter = require('iota.lib.js/lib/crypto/converter/converter.js')
const WConverter = require('iota.lib.js/lib/crypto/converter/words.js')

// Convert from trytes to bytes
seed = 'A999999999999TEST9999999999999999999999999999999999999999999999999999999999999999';
var trits = Converter.trits(seed);
var words = WConverter.trits_to_words(trits);

// Convert back to trytes from bytes
var reverted_trits = WConverter.words_to_trits(words);
var reverted = Converter.trytes(reverted_trits);

console.log(reverted);
// prints: VEETDFZJCUAXCERPEMET9999999999999999999999999999999999999999999999999999999999999
```

### Example
A simpler example is:
A99999999999999999999999999999999999999999999999999999999999999999999999999999999
that reverts back to:
J9JOEA999999999999999999999999999999999999999999999999999999999999999999999999999

The `Converter.trits(seed)` and `Converter.trytes(reverted_trits)` seem to work as expected, but `WConverter.trits_to_words(trits)` and `WConverter.words_to_trits(words)` are incompatible.

`WConverter.trits_to_words(trits)` returns this array:
```
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
01000000
```
But `WConverter.words_to_trits(words)` requires the following array to return A99999999999999999999999999999999999999999999999999999999999999999999999999999999:
```
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000000,
00000001
```

### Byte order
It looks like the byte order is the root cause, but which one is the correct one, I don't know.

**Comment by chrisdukakis** [comment]
WConverter is coupled to `Kerl` class and crypto-js implementation. It is not intended to be reused outside of Kerl. So Kerl has an additional step when lifting trits to word arrays: https://github.com/iotaledger/iota.lib.js/blob/develop/lib/crypto/kerl/kerl.js#L47
This change to your example should make it work:
```js
const CryptoJS = require('crypto-js')

const words = CryptoJS.lib.WordArray.create(WConverter.trits_to_words(trits)).words;
```

Ideally WConverter should be decoupled from Kerl, but such need didn't arise.

**Comment by vbakke** [comment]
True. Adding the ```CryptoJS.lib.WordArray.create(words).words``` fixes the endianess.
```javascript
const trits = Converter.trits(seed);
const words32 = WConverter.trits_to_words(trits);  
const words = CryptoJS.lib.WordArray.create(words32).words;  

const reverted_trits = WConverter.words_to_trits(words);
const reverted = Converter.trytes(reverted_trits);

console.log(reverted);
```
Still a bit funny that ```WConverter.words_to_trits(words)``` does not handle the output of  ```WConverter.trits_to_words(trits)```.


### Why on earth was I doing this...?
Totally agree that I'm diving into something that was not intended to be exposed.

I was trying to figure out how kurl made the transition from ternary to binary, so that it could use KECCAK-384. 

Myself, I've been looking at a way of encrypting an IOTA seed in [vbakke/tryte-encrypt](https://www.github.com/vbakke/tryte-encrypt) (similar to BIP-38 for Bitcoin).  So instead of rolling my own ternary-to-binary-and-back conversion.  I thought using existing and well accepted algorithms from the domain would be better.


### Conclusion
Unless you think that  ```WConverter.words_to_trits(words)``` should handle the output of  ```WConverter.trits_to_words(trits)```, just mark this as Won't fix.

**Comment by chrisdukakis** [comment]
Thank you for your response! For now `WConverter` is tested in integration with `Kerl` only. As such it isn't exported and shouldn't be used in other projects.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
