### ISSUE TITLE
getInputs return empty array

### ISSUE THREAD

**Issue by zeshanvirk** [iotaledger/iota.js#228]
https://github.com/iotaledger/iota.lib.js/#getinputs 

as per this documentation getInput should return all the addresses with balances but i;m getting empty array.

here is what i got: 
   "inputs": [],
   "totalBalance": 0

whereas i've multiple addresses in my seed and balance

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
