### ISSUE TITLE
Address validation strategy

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#245]
## Description
When it comes to address validation, uncertainty arises about validation options in various contexts, mostly because of [`isAddress()`](https://github.com/iotaledger/iota.lib.js/tree/e830d2e974f7e8bb4eef6234df082d7828160dae/packages/validators#module_validators..isAddress) implementation.

### Actual behaviour
[`isAddress()`](https://github.com/iotaledger/iota.lib.js/tree/e830d2e974f7e8bb4eef6234df082d7828160dae/packages/validators#module_validators..isAddress) verifies inputs with length of __81__ or __90__ trytes. In latter case `isAddress` does not validate the checksum.

### Expected behaviour
Address validation should require checksum validation.

## Change description
Validate addresses with `isValidChecksum()` of [`@iota/checksum`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/checksum) package.
Also, [`isHash`](https://github.com/iotaledger/iota.lib.js/tree/e830d2e974f7e8bb4eef6234df082d7828160dae/packages/validators#module_validators..isAddress) should change to verify strings of __81__ trytes only.

### Motivation
This change eliminates uncertainty around syntactic validation (hash tryte length=81) and integrity validation (checksum). It clarifies that address validation includes checksum validation.

### Requirements
- [ ] [`isHash()`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/)  verifies strings of __81__ trytes _only_.
- [x]  `validators.isAddress/isAddresses()` validates the checksum (https://github.com/iotaledger/iota.lib.js/pull/272)
- [ ] Replace `isHash(x)/isAddress(x)` with `isHash(removeChecksum(x))` on methods accepting both addresses with and without checksum and if validation _is not required_.
- [ ] Simply validate with `isValidChecksum()` in rest of methods that require validation.
- [ ] A solution should address issue #159 and any other similar cases.
- [ ] Documentation update (https://github.com/iotaledger/iota.lib.js/pull/272 , )

### Implementation remarks
- [ ] Consider performance of checksum validation in relation to throughput, particularly in cases of large sets (E.g: [`findTransactions({ addresses })`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.findTransactions)).

### Open Questions
- [ ] Which cases (mostly in [`core`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core)) should skip checksum validation? (see remark above)
- [ ] Which cases (mostly in [`core`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core)) should have _optional_ checksum validation?
- [ ]  Which cases should throw error if address is passed _without_ checksum? (E.g. [`prepareTransfers()`](https://github.com/iotaledger/iota.lib.js/tree/e830d2e974f7e8bb4eef6234df082d7828160dae/packages/core#module_core.prepareTransfers) [could be one](https://github.com/iotaledger/iota.lib.js/issues/159))

### Am I planning to do it myself with a PR?
Yes

**Comment by mrbianchi** [comment]
addresses without checksum should be avoided like bitcoin
bundles maybe should has a checksum too but with different calculation

**Comment by chrisdukakis** [comment]
hi @mrbianchi , thank you for your input! I agree that passing around addresses without checksum should be avoided. Bundles have integrity checks already, take a look at [`bundle-validator`](https://github.com/iotaledger/iota.lib.js/blob/c810a98636fe421f6d032ef705564a61a451e099/packages/bundle-validator/src/index.ts#L53).

**Comment by mrbianchi** [comment]
I mean, if you only have a hash of 81 length, you don't know if it is an address or bundle, you need request a node to know, and could be both

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.

**Comment by dartess** [comment]
@obany I wasted a lot of time, but I could not find an answer, what is the current way to check the validity of the address?

now we using `@iota/validators@1.0.0-beta.6`, but _actual_ version is [1.0.0-beta.30](https://www.npmjs.com/package/@iota/validators).

I wanted to see the changes and the current status of the project, and found that it was [gone](https://github.com/iotaledger/iota.js.git/tree/develop/packages/crypto).

After some more time of wandering, I am here. Please, help. Where can I find the current version of [isAddress](https://www.npmjs.com/package/@iota/validators#validators-isaddressaddress)?

**Comment by obany** [comment]
Those libraries are for the legacy versions of the network, there are no addresses any more.

**Comment by dartess** [comment]
Thanks for the very quick response!

To be honest, I only found out about iota today, so I don't know about the status. Therefore, just in case, I will clarify.

I am trying to refactor validation [cryptocoin addresses library](https://github.com/Swyftx/crypto-address-validator). It supports Iota addresses. Did I understand correctly that now the validation of Iota addresses does not make any sense and support for Iota should be removed? Or does "legacy versions of the network" exist in some form, and the validator could theoretically be useful to someone?

**Comment by obany** [comment]
The addresses used to be 81 trytes A-Z9 and are only supported in the legacy networks e.g. https://explorer.iota.org/legacy-mainnet/address/TRANSFERNELCK9EDC9IBDBJZZBSBLAIZTZUYIZPYABF9KDDWZDHVOYTCNAXCAWEWGVXXOXGYBDJAQEOY9 at some point this will be deprecated.

The current networks use the more standard mechanism for addresses of bech32 format starting with the `iota` prefix https://explorer.iota.org/mainnet/addr/iota1qpklumdlltn9mkmxmv2j34rtccv06c8eeatqn4fy44a0llzrwzx76t7yjqk
