### ISSUE TITLE
Paged requests/results

### ISSUE THREAD

**Issue by mrbianchi** [iotaledger/iota.js#248]
I think will be a good idea implements paged requests/results

Example, if I request transactions of this address:

https://thetangle.org/address/REATTACH9DOT9ONLINE99999999999999999999999999999999999999999999999999999999999MRB

I have to wait a lot of time and I can't get a progress feedback, even the lib stuck the tab in web explorer

Will be a good idea have params "from" and "to" , like insight Bitcoin explorer:
https://github.com/bitpay/insight-api#address

**Comment by chrisdukakis** [comment]
Hi @mrbianchi , this will be examined in relation to https://github.com/iotaledger/iri/issues/875

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
