### ISSUE TITLE
Define standard error responses

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#257]
### Description
Define standard error responses (codes & messages) under API versions. As mentioned in https://github.com/iotaledger/iri/issues/874 ,  [MS REST API Guidelines](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md) can be used, and particularly a solution according to this:

https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses

### Motivation

Error messages might change in IRI and brake various contracts that rely on naming conventions. An example of conventional contract can be found [here](https://github.com/iotaledger/iota.lib.js/pull/251#issuecomment-409191323). 
 
### Requirements
- [ ] Library should ship with supported API version.
- [ ] Error responses should be defined in IRI and pulled with automated script.
- [ ] API versions should be backwards compatible.

### Open Questions
- [ ] Define blocking tasks and estimate an ETA

### Am I planning to do it myself with a PR?
Yes

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
