### ISSUE TITLE
IOTA constructor silently ignores ":port" in "host" parameter

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota.js#263]
### Bug description
The IOTA constructor silently disregards the ":port" portion passed as the `host` parameter. Connecting to the default `14265` port instead in the absence of a `port` parameter, giving the user the impression that it tried to connect to the supplied port in the `host` parameter instead. 

### Steps To Reproduce
```
const IOTA = require('iota.lib.js');

const iota = new IOTA({
  'host': 'https://potato.iotasalad.org:14200'
})
```
Silently connects to default port `14265` instead.

### Expected behaviour
Either bail with "the `host` parameter is malformed" or actually connecting to the appended port. 

### Actual behaviour
Silently connects to default port `14265` instead, in the absence of a `port` parameter.

### Motivation
This is misleading for the user.

### Am I planning to do it myself with a PR?
Maybe

**Comment by th0br0** [comment]
Use `provider` instead

**Comment by chrisdukakis** [comment]
I'll just do a quick fix for it.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
