### ISSUE TITLE
Retry with larger depth if reference transaction is too old

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#264]
### Bug description
If `getTransactionsToApprove()` is called with an old reference in relation to a given depth, the call will sometimes fail with [`"Reference transaction is too old"`](https://github.com/iotaledger/iri/blob/06ad631a438b07e932ea3de58ffac6e4c5b6e74b/src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java#L123) exception. This has an impact on promotion with `promoteTransaction()` which doesn't recover after failure, assuming reference is still consistent.

### Steps To Reproduce
1. Call `getTransactionsToApprove()` with small depth on a relatively old reference
2. Promote a relatively old reference with small depth by calling `promoteTransaction()`

### Expected behaviour
`promoteTransaction()` should be able to recover as long as reference transaction is consistent & above max depth. It should recall `getTransactionsToApprove()` with larger depth (`<= maxDepth`).

### Actual behaviour
`getTransactionsToApprove()` fails with exception & `promoteTransaction()` stops working for relatively small depth.

### Requirements
- [ ] `promoteTransaction()` recovers from `"Reference transaction is too old"` exception, on _consistent_ txs, by increasing the depth up to `maxDepth = 15`

### Open Questions
- [ ] Should we enable retries by default in `getTransactionsToApprove()`?

### Am I planning to do it myself with a PR?
Yes

**Comment by chrisdukakis** [comment]
reopening for `next` branch

**Comment by ElvisPresly** [comment]
![screen shot 2018-12-21 at 09 53 30 am](https://user-images.githubusercontent.com/18265958/50329027-760cbe00-0506-11e9-8a7f-ff0694ef5119.png)

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
