### ISSUE TITLE
Incompatibility with MAM

### ISSUE THREAD

**Issue by michelpm1** [iotaledger/iota.js#276]
I'm Trying to use MAM with this lib but looks like they are incompatible is it?

<img width="878" alt="screen shot 2018-08-27 at 23 13 32" src="https://user-images.githubusercontent.com/4390192/44729076-60d1d680-aab4-11e8-84c8
-992e9275589a.png">

If yes, there is a way to use the old iota.lib?

**Comment by chrisdukakis** [comment]
Hi @michelpm1, please use `iota.lib.js`, until mam client is imported to iota.js monorepo.

**Comment by htreu** [comment]
> mam client is imported to iota.js monorepo

Afaik the MAM client itself is a fork and licensed under GPL 3. I don't think it can just be "imported", as iota.js is MIT (X11?) licensed.

**Comment by pph7** [comment]
@chrisdukakis how long will this take?

**Comment by chrisdukakis** [comment]
@pph7 I don't know yet because it makes sense to wait for MAM+. It's being written at the moment by Research Institute for Applied Problems of Mathematics and Informatics at Belarusian State University.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
