### ISSUE TITLE
Question abount "GetTransactionsObjects" Method

### ISSUE THREAD

**Issue by manthanomy** [iotaledger/iota.js#284]
There is many unit of IOTA like i, mi, ki, gi and etc.

**GetTransaction Method of iota api** return the transaction object with **value**

**_But how can programmer understand whether value is in i , ki, mi, or gi or in which unit._**

Please give an solution as soon as possible.

**Comment by chrisdukakis** [comment]
Hi @manthanomy , values are in iotas (i).

**Comment by manthanomy** [comment]
Thank you
