### ISSUE TITLE
Compatibility issues with React Native

### ISSUE THREAD

**Issue by rlech** [iotaledger/iota.js#285]
### Bug description
The @iota/core package is not working with react native but the iota.lib.js will work

### Hardware Spec
win10
node 8.11.4
expo-cli 2.2.0

### Steps To Reproduce
1. create a new app via `expo init my-app`
2. `yarn add @iota/core`
3. start "expo start"
4. try to import @iota core somewhere in your componets with `import { composeAPI } from '@iota/core'`

### Expected behaviour
import should not crash the app, composeAPI should be useable

### Actual behavior
app will crash when I import the package

### Errors
```
Can't find variable: self

<unknown>
<a-path>\node_modules\isomorphic-fetch\node_modules\whatwg-fetch\dist\fetch.umd.js:7:16
<unknown>
<a-path>\node_modules\isomorphic-fetch\node_modules\whatwg-fetch\dist\fetch.umd.js:2:73
<unknown>
<a-path>\node_modules\isomorphic-fetch\node_modules\whatwg-fetch\dist\fetch.umd.js:5:2
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\isomorphic-fetch\fetch-npm-browserify.js:5
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\@iota\http-client\out\http-client\src\request.js:12
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\@iota\http-client\out\http-client\src\httpClient.js:14:16
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\@iota\http-client\out\http-client\src\index.js:3:19
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\@iota\core\out\core\src\composeAPI.js:3:4
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\@iota\core\out\core\src\index.js:101:19
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<unknown file>:0
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\navigation\MainTabNavigator.js:9
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\navigation\AppNavigator.js:4
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\App.js:4
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
<unknown>
<a-path>\node_modules\expo\AppEntry.js:2
loadModuleImplementation
<a-path>\node_modules\metro\src\lib\polyfills\require.js:214:12
guardedLoadModule
<a-path>\node_modules\metro\src\lib\polyfills\require.js:141:45
global code
<unknown file>:0
```

**Comment by chrisdukakis** [comment]
Hi @rlech, thank you for opening this issue.
I noticed that `expo` downgraded `whatwg-fetch` (https://github.com/expo/expo/commit/56d705558060a8b7f42bef5b1839102aec69202a#diff-be8aab527a765993c92820a77f325029R95). I presume it might work if you force the same version (`"whatwg-fetch": "^2.0.4"`) in your project.

In any case it might be good to look for a platform agnostic fetch polyfill for `@iota/core`.

Also, please note that there are few compatibility issues with `react-native` in other `@iota` packages. For example `TypedArray.map` & `TypedArray.slice` do not work in on __android__. Those will be solved in https://github.com/iotaledger/iota.js/pull/286 .

**Comment by chrisdukakis** [comment]
Hi @rlech, I updated #286 to depend on [`cross-fetch`](https://github.com/lquixada/cross-fetch). I think this should solve the problem.

**Comment by chrisdukakis** [comment]
I've published a nightly release (based of https://github.com/iotaledger/iota.js/pull/286/commits/96000eb5bbe7c1628169deb0be370d936cdbc136 in #286) that is candidate for resolving the issue. If anyone wants to test please install with:
```
npm i @iota/core@1.0.0-beta.96000eb5
```
