### ISSUE TITLE
Define an interface for storage adaption

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#297]
### Description
Client should be database agnostic, to achieve this we need to define an interface.

The interface will be open for extension but closed for modification. For example some storage features will be added later, but altering existing structure would break storage adapters.

Interface could look like:
```TS
type IncrementKeyIndex = (store: any) =>
    () => Promise<Int8Array /* as trit encoded integer */>

type ReadPendingTransactions = (store: any) =>
    () => Promise<Int8Array /* as trit encoded transaction */>

type WritePendingTransactions = (store: any) =>
    (transactions: Int8Array) => Promise<Int8Array>

type DeletePendingTransactions = (store: any) =>
    (transactions: Int8Array /* as hashes */) => Promise<Int8Array /* as transactions */> 
```

Stored transactions should be (de)serialized. (De)serialization should be contained in interface definition.

### Requirements
- [ ] Method definitions
- [ ] (De)serialization definition

### Am I planning to do it myself with a PR?
Yes

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
