### ISSUE TITLE
Generate reference docs according to a layout

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iota.js#302]
### Description
We'd like to generate the reference documentation in this repo on every release. 

### Motivation
Have the documentation generated automatically.
Allow the documentation portal to pick up the new versions of the documentation on every release from this repo. 
Have reference docs in a layout that is consistent across the ecosystem.

### Requirements
- Documentation is generated in a *specified folder on every new release. 
- Documentation adheres to [specific layout](https://github.com/iotaledger/documentation/pull/94). Each method has its own .MD file generated.

**Note:** We only have to keep the latest generated version. All previous versions will be persisted in the `iotaledger/documentation` repo.  

### *Folder structure
The docs should be generated in the following folders in this repo:
/docs/<project_name>/reference/<version>/<api_file>.MD

Later on, examples will be placed in:
/docs/<project_name>/examples/<api_file>.MD

**Comment by rajivshah3** [comment]
https://esdoc.org/ might be good for this

**Comment by chrisdukakis** [comment]
Hey @rajivshah3, it's a nice tool. But I think using https://github.com/Microsoft/tsdoc aligns better with codebase written in TypeScript. It's pre-release software but has elegant features, and it's up to the community to enhance it rapidly. I'm confident that this will be the case because we need it:
https://github.com/Microsoft/tsdoc#why-do-we-need-tsdoc

**Comment by rajivshah3** [comment]
Ooh, I didn't know that existed (I haven't looked into TypeScript at all). That definitely looks better

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
