### ISSUE TITLE
http-client: Get errors with their data

### ISSUE THREAD

**Issue by viossat** [iotaledger/iota.js#303]
### Bug description

Nodes can return errors (HTTP status >= 400) with valid JSON. However those data are dropped by the http-client package.

https://github.com/iotaledger/iota.js/blob/2ad21079c655f7c7527ad392d896b85e257f9f34/packages/http-client/src/request.ts#L43-L44

### Steps To Reproduce

```js
api.getTransactionsToApprove(42000)
    .then(console.log)
    .catch(console.error)
```

### Expected behaviour

A way to get the returned JSON `{"error":"Invalid depth input","duration":0}`

### Actual behavior

The only available thing is a string `Request error: Bad Request`

**Comment by chrisdukakis** [comment]
Hi @viossat and thanks for reporting!
I opened #304 which should fix the issue.
