### ISSUE TITLE
Incorrect default input security level in 'prepareTransfers' & imprecise security level validation

### ISSUE THREAD

**Issue by cym00n** [iotaledger/iota.js#325]
### Description
- If the ``inputs[].security`` option in ``prepareTransfers()`` is omitted, it always defaults to ``1``. 
- Security levels are only validated to be any positive integer.

### Expected behavior
- The default value of ``inputs[].security`` should be the value of the ``security`` option, which defaults to ``2`` if omitted.
- There should be an error if security levels above ``3`` are specified, to make it more difficult for users to create invalid bundles by mistake. Furthermore the ``isSecurityLevel()`` guard should also be applied to ``core.generateAddress()`` and other functions where security levels can be specified.

### Steps To Reproduce
Version: `1.0.0-beta.7`.
* The following arguments sign the input with security level ``1``.
 ```js
prepareTransfers(seed, [{
    value: 1000,
    address: to_address,
  }], {
    inputs: [{
      address: from_address,
      keyIndex: from_address_index,
      balance: 1000,
      // security: 2
    }],
    security: 2
  })
```

* The following arguments return bundle trytes, which could potentially leak valid signatures from invalid bundles and make users sign inputs repeatedly.
 ```js
prepareTransfers(seed, [{
    value: 2000,
    address: to_address,
  }], {
    inputs: [{
      address: from_address,
      keyIndex: from_address_index,
      balance: 1000,
      security: 2
    }, {
      address: from_address2,
      keyIndex: from_address_index2,
      balance: 1000,
      security: 4
    }],
    security: 2
  })
```

### Am I planning to fix it myself with a PR?
Please check the commits in the following branch: https://github.com/cym00n/iota.js/commits/fix/prepareTransfers
- I created a fix for the default security levels in ``prepareTransfers()`` giving correct results in my tests: https://github.com/cym00n/iota.js/commit/81f8fc24b77d7627c1ad648347e47c5a599c1a21.
- Made the ``isSecurityLevel()`` guard more precise: https://github.com/cym00n/iota.js/commit/61156db21fabd911e09e79cb318331e0393264fd. (It is not applied to ``generateAddresses()``, yet)
- Added the default value of the ``security`` option to the docs: https://github.com/cym00n/iota.js/commit/f203e922f4e40080072e8eb20498645e93315b33. (It should be added that ``inputs[].security`` defaults to the value of the ``security`` option.)
- Corrected some unrelated mistakes/typos in the docs: https://github.com/cym00n/iota.js/commit/58e8164d74c95e43cf5296b74949161e87cf351d.
- Updated the README.md files using ``npm run docs`` but noticed there are formatting issues in some of the files. Not sure what went wrong. Example: https://github.com/cym00n/iota.js/commit/d40a69adda59d301626ae6ac2e1470281eef0047#diff-ad6abd4cf0c4d1dddba0d9255a85f596L30.

I will try to make necessary changes and a pull request once I have received feedback.

**Comment by chrisdukakis** [comment]
Hi @cym00n thank you for finding this bug!
I think that we should throw error in case security is missing from input object. Security level of _given_ input should be defined explicitly and not assumed.

**Comment by chrisdukakis** [comment]
@cym00n I opened 326 which makes input objects require a security level.
I also agree with your fix for security level validation. Would be good to have it in `generateAddress()` too! Please create a PR for this and your doc fixes (could be another PR).

Wrt formatting of README, nothing went wrong, I have a vim [plugin](https://github.com/godlygeek/tabular) which prettifies table alignment and seems I've opened the readme in vim once.

**Comment by cym00n** [comment]
Hi @chrisdukakis I want to make a pull request for my changes to the docs, but I still have some questions with regard to formatting of README files.

It looks like prettifying of staged `.md` files was recently introduced with these two commits: 
https://github.com/iotaledger/iota.js/commit/788464db6ccacc8321ce2bd8670468e1033ac6b4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
https://github.com/iotaledger/iota.js/commit/5647d32d43f1a640828d82a236167fa5b5da5def#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Do you think it should be kept like this or should `.md` files be removed from `lint-staged` so the README files are not modified after being generated with `npm run docs`?

It is confusing to me that the prettifier changes the headings and turns for example 
``### *bundle-validator*~isBundle(bundle)`` into ``### _bundle-validator_~isBundle(bundle)``
which looks different in the [bunde-validator README](https://github.com/cym00n/iota.js/blob/87694b305925202aa317931c496f697bf9fe5955/packages/bundle-validator/README.md) and the [core README](https://github.com/cym00n/iota.js/blob/87694b305925202aa317931c496f697bf9fe5955/packages/core/README.md) even though the headings use underscores in both files. I don't understand why that happens.

I created two branches, [with prettifying](https://github.com/cym00n/iota.js/commits/docs/corrections) and [without prettifying](https://github.com/cym00n/iota.js/commits/docs/correctionsNotPrettified). Please let me know which one I should use for my pull request.

Also, in order to generate the docs, I had to install ``jsdoc2md`` manually by running ``npm install jsdoc-to-markdown``. Should this package be added to ``devDependencies``?

**Comment by chrisdukakis** [comment]
Hi @cym00n , I disabled prettier for staged markdown files (https://github.com/iotaledger/iota.js/pull/330).
It's ok to leave md files a bit ugly for now :)
