### ISSUE TITLE
prepareTransfers replaces the message with signature parts at 0 value transactions

### ISSUE THREAD

**Issue by 7h7** [iotaledger/iota.js#328]
### Bug description
prepareTransfers adds signature parts at 0 value transactions if you pass an inputobject with security >1 and balance >0 and replaces the message

### Steps To Reproduce
1. Use `const transfers = [{
        address: 'EXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDR',
        value: 0,
        message: Converter.asciiToTrytes('Example message'),
        tag: 'TAG'
},{
    address: 'EXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDRESSEXAMPLEADDR',
    value: 0,
    message: Converter.asciiToTrytes('Example message'),
    tag: 'TAG'
}]` 
and 
`const options = {
    'inputs': [{
        address: Iota.generateAddress(seed, 0, securitylvl, false),
        keyIndex: 0,
        balance: 1,
        security: securitylvl,
        tag: 'TAG'
    }]
}`
in 
`prepareTransfers(seed, transfers, options)`
2. Use security level 2 and 3
3. Look at the result

### Expected behaviour
It should ignore the input options and create the bundle with the messages
Example: https://thetangle.org/bundle/MVAYCHVI9OVK9BW9P9CTJLSHHLTEKGGPZOUWRIWWVXWALWTGDATUGJQWBWOKGJSEHTTVSL9JBDCBLFWNX

### Actual behavior
With security level 2 the message of the first transaction is replaced and with security level 3 both messages are replaced by signatureparts

Example with sec. lvl. 2: https://thetangle.org/bundle/YLDLY9ZWCIVLBZPD9IFKNVTHBKOSKOWJFUKBSY9LYRWIW9JCYHXUKXJXYKNIRROBVRYFCJLZRXJILJHOC
Example with sec. lvl. 3: https://thetangle.org/bundle/HGQQAOGFGTFJYXHGHRLCUNLHWBDZMJZK9LQBJGRRWPNGIWLHJTBQSHMQL9IJLJCGTWPKE9WQ9YXIXGTAW

**Comment by chrisdukakis** [comment]
Hi @7h7 , thank you for reporting this issue.
I'm not in favour of ignoring the input, because the problem could be in transfers.
Another idea is to send to a new remainder address. This could be used for sweeps.

**Comment by chrisdukakis** [comment]
I created #329 which sweeps any input value in this case.

I like this idea more, because an implementation might assume that any inputs given to `prepareTransfers()` should be already marked as used.

Please take a look at the [test](https://github.com/iotaledger/iota.js/pull/329/files#diff-f600f2e516a7e244fcd4e93b19670e05R145) to see how it's supposed to work.

**Comment by allemanfredi** [comment]
i had the same problem. How can i do to solve it?

**Comment by Thoralf-M** [comment]
@allemanfredi remove the inputs in the options object

**Comment by allemanfredi** [comment]
@7h7 it works, thank you very much!

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
