### ISSUE TITLE
Nocks in core integration tests uses hardcoded sample data

### ISSUE THREAD

**Issue by sachushaji** [iotaledger/iota.js#332]
### Description
Some of the nocks which are used for integration tests at core uses hardcoded sample data.
For eg, the following nocks
 - findtransaction.ts
 - getBalances.ts
 - prepareTransfer.ts
 - wereAddressSpentFrom.ts

They use samples which are already present in the '@iota/samples' itself but are hardcoded into the nocks. We can make it in such a way that it is fetched from the '@iota/samples'

### Motivation
If in future any breaking changes happens, you would only want to update '@iota/samples' and do not worry about changing samples anywhere else.

### Requirements
 - Every test will take the samples for testing from the '@iota/samples' and will make it easy to update samples data in future.

### Am I planning to do it myself with a PR?
Yes

**Comment by chrisdukakis** [comment]
Hi @sachushaji , this is a good idea!

**Comment by sachushaji** [comment]
Great , Will do a PR
