### ISSUE TITLE
No error with invalid addresses

### ISSUE THREAD

**Issue by 7h7** [iotaledger/iota.js#341]
### Bug description
No error from the lib if you want to send value to an invalid address

### Steps To Reproduce
1. Try to send value to an address of which the last trit is not 0 (-1 or 1)

### Expected behaviour
An error should be returned stating that the address is invalid

### Actual behavior
The bundle is be completed and an error is returned when sending to the node

### Errors
`Request error: Bad Request`

**Comment by rajivshah3** [comment]
Additional info: https://github.com/iotaledger/trinity-wallet/issues/866
