### ISSUE TITLE
Typescript config ECMAScript target version

### ISSUE THREAD

**Issue by nmeylan** [iotaledger/iota.js#352]
Hello,

in **tsconfig.json** is there any reason to target ES3 ECMAScript version? as described in https://www.typescriptlang.org/docs/handbook/compiler-options.html **ES3** is the default value and when target is **ES3** or **ES5**, the module system used is **CommonJS**. 

While this works, this has an impact on bundle size for web usage. 
Indeed, webpack can perform [tree-shaking](https://webpack.js.org/guides/tree-shaking/) when using ES6 imports, but not when using CommonJS imports (the [webpack-common-shake](https://github.com/indutny/webpack-common-shake) is not really efficient)
I have tested by setting `"target": "ES6"` in tsconfig.json, and my final web's bundle has reduced by 80ko which is pretty nice. Sure the size reduction depends on the `import` you do in your code.

In addition, modern version of nodejs supports ES6 import.

So, can we consider to target ES6 version instead of ES3? or any concern to continue targeting ES3?

**Comment by chrisdukakis** [comment]
Hi @nmeylan, this is a valuable observation, however esm is still an experimental feature in node.js and requires `--experimental-modules` flag to work. Perhaps this can wait a bit.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
