### ISSUE TITLE
asciiToTrytes() can not convert ascii degree symbol °

### ISSUE THREAD

**Issue by iotlabo** [iotaledger/iota.js#367]
### Bug description
const Converter = require('@iota/converter')
[..........]
trytes = Converter.asciiToTrytes('28 °C');

When called the program crashes without errors. The degree symbol should be ASCII.

If I use utils.toTrytes() from iota object (library iota.lib.js) everything works

### Hardware Spec
On what hardware is the node running on?
Raspberry (Raspbian)

**Comment by chrisdukakis** [comment]
hi @iotlabo thank you for opening an issue. That's expected behaviour for `asciiToTrytes()`. It doesn't support extended ascii set because of compatibility issues with utf-8 which other software may use.
The problem will be solved once bits <-> trits conversion is standardised.
