### ISSUE TITLE
Light Node Optimization

### ISSUE THREAD

**Issue by atypicalprogrammer** [iotaledger/iota.js#38]
The library needs to be optimized for light nodes. 

- Cache whatever can be cached.
- Optimize the calls to the light node server. For example, instead of calling getTrytes with a single hash, combine all hashes into an array and call getTrytes 1 time. Same is probably true for other API methods such as findTransactions.

Right now, there are several overloaded light nodes which causes a lot of HTTP error 500 errors which in turn cause the wallet to malfunction.

**Comment by anyong** [comment]
[Batching](https://github.com/iotaledger/iota.lib.js/blob/next/lib/utils/request.ts#L56) has been added into v1.

@chrisdukakis what do you think about adding an optional cache to the request module?

**Comment by chrisdukakis** [comment]
`getTrytes()`, `findTransactions()` etc.. support arrays of hashes  already. But when traversing to fetch bundles for example, aggregating all hashes is not possible, as trunk transactions arrive over time.

@anyong we can do that and cache transaction history and inclusion states of confirmed transactions only, other resources are subject to change.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
