### ISSUE TITLE
Initial problems in running sample code

### ISSUE THREAD

**Issue by pwalimbe** [iotaledger/iota.js#384]
Please refer to the #362 (closed) but have added another comment there.

**Comment by chrisdukakis** [comment]
```
import { composeAPI } from '@iota/core'
^

SyntaxError: Unexpected token {
at Module._compile (internal/modules/cjs/loader.js:749:23)
```

Hi @pwalimbe, use `require { composeAPI } = '@iota/core'`, or check [Babel](https://babeljs.io/).
