### ISSUE TITLE
attachToTangle definition is incorrect

### ISSUE THREAD

**Issue by obany** [iotaledger/iota.js#389]
Either the definition of attachToTangle need amending or the way it is called needs correcting. The definition includes a callback parameter, but this is never actually used.

https://github.com/iotaledger/iota.js/blob/7a336ba4dd38c865c7ef3c478d74cc89ca65f7f3/packages/types.ts#L297-L304

The callback parameter is never actually used when the attachToTangle method is called, it is always called async.

https://github.com/iotaledger/iota.js/blob/fbd5d146e09625f0bef211fe95e838a339248b96/packages/core/src/createSendTrytes.ts#L89-L92

Any references in the comment that mention `ccurl.interface.js` as a local alternative for PoW is technically incorrect as the PoW method in that lib requires a callback. It could be wrapped with a promise to make it behave but it is not a simple drop in solution. `curl.lib.js` already returns a promise.

**Comment by chrisdukakis** [comment]
Hi @obany let's just remove callback from `AttachToTangle` interface?

**Comment by obany** [comment]
I agree that's probably the best solution, simplifies :)

**Comment by chrisdukakis** [comment]
Thank you, I'll make this change and update `ccurl.interface.js` too.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
