### ISSUE TITLE
MAM Econnrefused

### ISSUE THREAD

**Issue by mhamon002** [iotaledger/iota.js#390]
Hi,

I'm trying to use the MAM client (js), but i got a problem to attach a message to the tangle :

"FetchError: request to https://nodes.devnet.thetangle.org:443/ failed, reason: connect ECONNREFUSED 35.187.163.51:443"

I think that's a proxy problem but i configured npm with that proxy, so i don't know what can i do.
Thanks

**Comment by laumair** [comment]
@mhamon002 Which version of MAM client are you using?

**Comment by JakeSCahill** [comment]
@mhamon002 @laumair I think that was a community Devnet node, which is no longer active.

You should try the IF node: nodes.devnet.iota.org
