### ISSUE TITLE
Binance withdrawal

### ISSUE THREAD

**Issue by urbanet74** [iotaledger/iota.js#400]
I sent my iota from binance to my new trinity wallet that works with my ledger nano ......I haven't received nothing yet and most than 45 minutes are gone and my transaction is in processing mode.....what should I doing?

**Comment by NemesisFLX** [comment]
You are asking this in the wrong place.
Maybe go to the discord [server](https://discordapp.com/channels/397872799483428865) if you still have the problem and ask there in #general.
