### ISSUE TITLE
List of closed and open cdas

### ISSUE THREAD

**Issue by NemesisFLX** [iotaledger/iota.js#409]
### Description
As a developer of a wallet application i propably wanna have a list of "closed" and "open" cdas. So cdas that are currently not timed out are open and closed ones are the ones that got money in them as the ones that didnt receive any are thrown out of the database.

The same list for closed and open withdraws propably. ( But have not worked with sending )

### Motivation
Every wallet application needs a history and even if it runs on a sensor. Someone propably want to check up on it from time to time.

### Requirements

- [ ] List of closed cdas ( or confirmed )
- [ ] List of open cdas ( or pending )

### Open Questions (optional)
Some of it is propably already implemented because the `account.on('includedDeposit' )` already sends this information on startup ( without the timestamp just the history ), but then i need to store this information in my application. I would like to get this information from the persistence provider on demand.

### Am I planning to do it myself with a PR?
No, (maybe i could try, but have no experience in typescript )

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
