### ISSUE TITLE
Is it possible to get all transactions with a part of the tag?

### ISSUE THREAD

**Issue by hotu14** [iotaledger/iota.js#410]
Hey,
i'm currently sending data in a private tangle with the tags "name_date" for example "abc_20190712". To send that i had to convert the tag to trytes before sending. 

How do i get all transactions from a certain address by searching only after a part of the tag, i.e. i would start the script with "node recieve.js 201907" and get all the transactions from the specified address that has the "201907" in it?

**Comment by chrisdukakis** [comment]
Hi @hotu14 , you can query by address and filter by tag: 
```JS
findTransactionObjects({ addresses: [address] })
  .then(txs => txs.filter(tx => tx.tag.indexOf('TRYTES') > -1))
```

**Comment by hotu14** [comment]
Hello @chrisdukakis , thank you very much. what does the filter return, since i'm getting an `invalid trytes length error`. also does the library have a function to loop through the data or is a for loop enough?


```
const search = Converter.asciiToTrytes('201907');
iota.findTransactionObjects({ addresses: [address] })
  .then(txs => txs.filter(tx => tx.tag.indexOf(search) > -1))
  .then(data => {
    for(let elem in data){
     const datatag = Converter.trytesToAscii(data[elem].tag)
     console.log(datatag);

     const datainfo = Converter.trytesToAscii(data[elem].signatureMessageFragment)
     console.log(datainfo);
    }
   })
  .catch(err => {
   console.error(err);
  })
```

**Comment by chrisdukakis** [comment]
Hi @hotu14 , 
- the filter returns transactions that have `asciiToTrytes('201907')` in their `tag`. I think the error comes from this line:
```JS
iota.findTransactionObjects({ addresses: [address] })
```
Did you specify an address?

- You can use this to iterate:

```JS
.then(data => data.forEach(transaction => {
    // ...
})
```

- Finally the script will fail at this line anyway:

```JS
const datainfo = Converter.trytesToAscii(data[elem].signatureMessageFragment)
```
`trytesToAscii()` input should be trytes of even length and `signatureMessageFragment` has odd length.

**Comment by hotu14** [comment]
Hello @chrisdukakis thanks again. It wasn't the address but indeed the odd length of the tag and the signaturemessagefragment. It runs now.
```
iota
  .findTransactionObjects({ addresses: [address] })
  .then(txs => txs.filter(tx => tx.tag.indexOf(search) > -1))
  .then(data => data.forEach(transaction => {

    console.log(Converter.trytesToAscii(transaction.tag.slice(0,-1)));
    console.log(Converter.trytesToAscii(transaction.signatureMessageFragment.slice(0,-1)));
   }))
  .catch(err => {
   console.error(err);
  })
 
```

**Comment by chrisdukakis** [comment]
Great, I think we can close this issue.
