### ISSUE TITLE
Check for used Addresses

### ISSUE THREAD

**Issue by awiech** [iotaledger/iota.js#433]
I need to check if an address was ever withdrawn from. Is there a convenient way to do this or do I have to use the http-client to send the command directly to IRI?

Thanks

**Comment by laumair** [comment]
@awiech There are multiple ways to check if an address was spent from. 

1. Use [findTransactionObjects()](https://github.com/iotaledger/iota.js/blob/next/api_reference.md#module_core.findTransactionObjects) and check if any transaction has negative value
2. Use [wereAddressesSpentFrom()](https://github.com/iotaledger/iota.js/blob/next/packages/core/src/createWereAddressesSpentFrom.ts)

_1_  would fail if the node you are querying has snapshotted and doesn't contain the transaction history associated with your address. 

```
const Iota = require('@iota/core');

const address = 'LEYNSIMADMXAUYRGXKKEXPHDMZLRISZBSRZXUMCIKP9JQDOXSCIUGKYFFNPPVPGCHEJAWWSDHCKGOORPCX9WQZZEHY';

const iota = Iota.composeAPI({
    provider: 'https://mama.iota.family:14267'
});

iota.findTransactionObjects({
    addresses: [address]
}).then((transactions) => {
    const isUsed = transactions.some((transaction) => transaction.value < 0);

    return iota.wereAddressesSpentFrom([address])
}).then(console.log);
```

Hope that helps.

**Comment by laumair** [comment]
Please feel free to reopen if there's any other confusions regarding this topic.
