### ISSUE TITLE
check value txs for Kerl address

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota.js#437]
prepareTransfers doesn't check for Kerl addresses in value transactions, only the bundle-validator does it
https://github.com/iotaledger/iota.js/blob/f299715f6b89deda345c5cb633e400c4423052fd/packages/bundle-validator/src/index.ts#L74

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
