### ISSUE TITLE
Sending message with CDA payments.

### ISSUE THREAD

**Issue by KhushalPShah** [iotaledger/iota.js#450]
### Description
The present account module allows to make a payment to a CDA, with the sendToCDA() method. 
However, there is no provision to send a message(via the message field of the transaction) along with the tokens to the CDA.

### Requirements
A field in the CDA object to allow sending message to the CDA while making the payment.

### Am I planning to do it myself with a PR?
Yes(but i need a bit of guidance for the same).

**Comment by chrisdukakis** [comment]
Hi @KhushalPShah we can add a message field, but delivery of it as part of the payment is not guaranteed. Message fragments are not part of the essence (the part of the bundle that is hashed, normalized & signed), and an adversary might reattach the bundle with a different message.

**Comment by KhushalPShah** [comment]
Thanks for the response @chrisdukakis .
So, the message field is unsafe to use for transactions?
Is there any other alternative to send a message to a CDA?
In essence, as an issuers of a CDA, I need to know from which account is the payment coming?

**Comment by chrisdukakis** [comment]
> So, the message field is unsafe to use for transactions?

Yes the message lacks authentication, hence you can't use it as identifier for depositors.
You can identify depositors by assigning addresses to them. Ideally, we could utilize messaging by adding mam support to account.

You can still open a pull request, to add a field for `tag`, which is missing. Unlike messages, tags are part of the essence. This can be done by passing tag as a property [here](https://github.com/iotaledger/iota.js/blob/1c3a68e1ada2f3a6db387c109832e85e920ce7e2/packages/account/src/preset.ts#L221), and modify the [`CDATransfer` type](https://github.com/iotaledger/iota.js/blob/next/packages/cda/src/cda.ts#L32).

**Comment by KhushalPShah** [comment]
Alright.
I will work on it and open a pull request then.
Thanks @chrisdukakis

**Comment by Thoralf-M** [comment]
Only the obsolete tag is part of the essence

**Comment by chrisdukakis** [comment]
That's actually correct, but we refer to it as "tag" in transfer objects; https://github.com/iotaledger/iota.js/blob/1c3a68e1ada2f3a6db387c109832e85e920ce7e2/packages/core/src/createPrepareTransfers.ts#L247

**Comment by Thoralf-M** [comment]
Is this not changed for index 0 when searching for a bundle hash without M?

**Comment by chrisdukakis** [comment]
It does, but this will change with future protocol upgrades. We could also reverse the tag and use some of the 27 trytes. I think only few first trytes are changed.

**Comment by KhushalPShah** [comment]
Adding an obsoleteTag property will allow the bundle to be secured(in a way that any adversary will not be able to reattach a same bundle) as well allow the CDA issuer to identify the depositor?
Is that right @chrisdukakis  @Thoralf-M ?

**Comment by Thoralf-M** [comment]
Every bundle can be reattached, and the part in the message could be changed, but the part in the obsoleteTag not. But if you set the obsoleteTag it could be changed at the bundle creation (that's done at index 0, that could theoretically changed to the index with the input transaction, so it has no impact to the set value)

**Comment by chrisdukakis** [comment]
> as well allow the CDA issuer to identify the depositor
@KhushalPShah  It only provides assurance that obsoleteTag was written by the one who signed the bundle.
Plus it will need some more tweaks, to work around the issue @Thoralf-M explained.

**Comment by KhushalPShah** [comment]
So, is there any other way to identify the depositor?

**Comment by chrisdukakis** [comment]
Assigning an address to each depositor should work. You could store an address alongside some meta, like who the depositor is. Then just wait for the expected balance to arrive and credit to the assigned name.

**Comment by KhushalPShah** [comment]
In that case, I won't be able to use the multiUse type CDA, since I won't be able to keep a track of who deposits.

**Comment by chrisdukakis** [comment]
That's a correct observation I think.
Another thing to consider about multiuse, is that tokens from individual deposits cannot be utilized before the timeout is over.

**Comment by KhushalPShah** [comment]
@Thoralf-M  @chrisdukakis 
Me being new to the IoTA environment, I couldn't quite understand your concerns for not using the ObsoleteTag for sending information about the depositor.
So, I tried a transaction, which uses the ObsoleteTag field and set it to a certain value.
And, I found the ObsoleteTag unchanged on the Tangle.
JS Code Snippet:
`const transfers = [
    {
      value: 10,
      address: receivingAddress,
      message : message,
      tag : "SENTFROMSONYPCSENTFROMSONYP"
    }`
Transaction On Devnet Tangle:
[https://devnet.thetangle.org/transaction/TTYGWYOOQTFPHJLSARMBTWZIT9CWRTVBNRJKGNYHZBXSTWTERFSZGCDFKCCHLIZMUPXMLDK9IMXZSM999](url)

Can you explain this?
Also, if you can provide some documentation about your point, that would be really great!
Thanks.

**Comment by Thoralf-M** [comment]
The obsolete tag of this transaction is "REOTFROMSONYPCSENTFROMSONYP"

**Comment by KhushalPShah** [comment]
What is the Tag field seen on the Transaction in the Tangle? 
Also, how does Tangle explorer show it unchanged, even though the Bundle shows a change?

**Comment by chrisdukakis** [comment]
It's another field which isn't included in the essence, and was planned to be replacement of "obsoleteTag". To get a better overview about transaction fields please have a look in this docs section: https://docs.iota.org/docs/getting-started/0.1/transactions/transactions
