### ISSUE TITLE
typings of @iota/extract-json can not be found 

### ISSUE THREAD

**Issue by Xiphe** [iotaledger/iota.js#455]
### Bug description
When importing from `@iota/extract-json` `v1.0.0-beta.23` in typescript, I get the error `Could not find a declaration file for module '@iota/extract-json'.`

### Hardware Spec
I'm developing on MacOS 10.14 && node@12

### Steps To Reproduce
1. setup a typescript project with this `tsconfig.json` (I copied the [config from this project](https://github.com/iotaledger/iota.js/blob/next/tsconfig.json))
```
{
  "compilerOptions": {
    "lib": ["dom", "es2015"],
    "noImplicitThis": true,
    "strict": true,
    "outDir": "out",
    "typeRoots": ["node_modules/@types"],
    "declaration": true,
    "declarationDir": "typings",
    "sourceMap": true
  }
}
```
2. `npm install @iota/extract-json@1.0.0-beta.23`
3. create a typescript file
```ts
import { extractJson } from "@iota/extract-json";
```

### Expected behaviour
I would expect to have typings for the package

### Actual behavior
I don't get typings but instead an error

### Errors
I receive an error `error TS7016: Could not find a declaration file for module '@iota/extract-json'.`

---

If someone can confirm that this is a bug, I'd be happy to dig into it and provide a PR to fix it.

**Comment by chrisdukakis** [comment]
Hi @Xiphe thanks for opening an issue. The typing directory is wrong: https://github.com/iotaledger/iota.js/blob/d42eb4ac7e6fb23fedb4bbd0caa05e1ae9ee45b3/packages/extract-json/package.json#L6
It should be `./typings/extract-json/src`.
