### ISSUE TITLE
getBalances will no longer require a threshold

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/iota.js#463]
### Bug description
In this [PR](https://github.com/iotaledger/iri/pull/1768#pullrequestreview-365391016), the `threshold` parameter is removed from the getBalances endpoint on IRI nodes.

Currently, this is a required parameter is the library, so we should make it optional.

### Expected behaviour
The `threshold` parameter is optional (for backwards compatibility)

### Actual behavior
The `threshold` parameter is required

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
Fixed in #481
