### ISSUE TITLE
Security alert for crypto-js version < 3.2.1

### ISSUE THREAD

**Issue by anhcao142** [iotaledger/iota.js#465]
### Description
I'm doing a security check for my repo and this alert shows up which requires upgrading crypto-js to v3.2.1 or higher. You can read more about this security issue here https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472

### Requirements
This is fixed for crypto-js version > 3.2.1, so please upgrade crypto-js to at least v3.2.1

### Am I planning to do it myself with a PR?
No

**Comment by laumair** [comment]
Related https://github.com/iotaledger/iota.js/pull/469 & https://github.com/iotaledger/iota.js/pull/460

**Comment by laumair** [comment]
Updated to v4.0.0 in https://github.com/iotaledger/iota.js/pull/460.
