### ISSUE TITLE
getNewAddress() soon becomes extremely slow

### ISSUE THREAD

**Issue by andywer** [iotaledger/iota.js#50]
Since `getNewAddress()` creates addresses one-by-one and calls `findTransactions()` on every single one of them, it is slow even when there are not so many addresses.

### Possible solution

- don't create them one-by-one, but batches of five or so (in expectation that the first one might be used already)
- if the newly created address(es) are taken then do not `index++`, but try if `index * 2` is free and do a binary search between `index` and `index * 2`

**Comment by bmavity** [comment]
If you just want the actual address without the rest, you can use the _newAddress function instead: https://github.com/iotaledger/iota.lib.js/blob/45d5214a10f7a14da7121c2f2b30e7c448ee36ef/lib/api/api.js#L685

**Comment by andywer** [comment]
We need the checks, though, I fear. We just need them to be performed in a rather efficient manner 😉

(Btw, I would try not to use undocumented internal methods)

**Comment by bmavity** [comment]
I need it to pregenerate addresses for my iota wallet, so I have no other option. Besides, the method should be public. This library needs an api review.

**Comment by kgrsajid** [comment]
@andywer You need to check all the possible options for `getNewAddress()`, since it returns a lot of things apparently. Don't just rely on their unstable documentation.
@bmavity You can get the unused address without the checks also with `getNewAddress()`. Just experiment with it.

Or, just live with this slowness. 🐌 🐌 🐌

**Comment by anyong** [comment]
This is _addressed_ (bad pun intended) in the `next` branch, please give it a try!

https://github.com/iotaledger/iota.lib.js/blob/next/test/api/getNewAddress.test.ts#L35-L41

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
