### ISSUE TITLE
Removal of checkConsistency 

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota.js#529]
## Description

CheckConsistency is being removed from Hornet for Chrysalis pt 1.
We need to have a PR ready for this once it is released

**Comment by laumair** [comment]
@kwek20 It looks like it will not be removed for compatibility reasons. 

https://github.com/gohornet/hornet/pull/608/commits/952a4313bd28ff432ed39c0f724472ed871ec13f

**Comment by kwek20** [comment]
Yes i saw, Lets leave the issue open for now until we decide to never do it :) @laumair

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
