### ISSUE TITLE
Possibility to use bytes to set index

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iotaledger/iota.js#586]
## Description

As far as I can see, in the high level APIs I can only set an index for an indexation payload from a string. I need a way to hand over plain bytes.

## Motivation

I want to replace mam.c in my application. Therefore I need to publish a message to an index that equals a public key derived from a signature mechanism.

## Requirements

Write a list of what you want this feature to do.

1. Allow me to set an index from plain bytes, not only from a string

## Open questions (optional)

I believe this will be used a lot. Indezes dont neccessarily have to be readable.

## Are you planning to do it yourself in a pull request?

No

**Comment by obany** [comment]
The latest high level operations operate using bytes as hex instead of UTF8
