### ISSUE TITLE
prepareTransfers only takes 81-tryte addresses

### ISSUE THREAD

**Issue by hyperreality** [iotaledger/iota.js#61]
In the docs for prepareTransfers it says:

"If you provide an address with a checksum, this function will automatically validate the address for you with the Utils function isValidChecksum."

But then also "address: String 81-tryte encoded address of recipient"

The second of these contradictory statements is actually true since Kerl. If you provide a 90-tryte address in any of these fields, Kerl throws a cryptic error "Error: Illegal length provided", but with 81-tryte addresses it works.

**Comment by chrisdukakis** [comment]
This should be addressed in TS port. Discussion started here: #159

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
