### ISSUE TITLE
core.findTransactions API has a limited response size (1000 transactions)

### ISSUE THREAD

**Issue by CaixiangFan** [iotaledger/iota.js#642]
## Bug description

When I use the API findTransactions(address) to query transactions, it returns a limited response size, which is 1000 transactions. This is related to another [issue](https://github.com/iotaledger/iri/issues/1739). I am wondering how can I get more transactions than the limit?

## Version

1.0.0-beta.8

## IOTA network

Private tangle with hornet nodes.

## Steps To reproduce the bug

1. send iota to an address for over 1000 times.
2. query that address and only get 1000 transactions as response. 

## Expected behaviour

Get all hashes of transactions of that address.

**Comment by obany** [comment]
That is a limit of the node that you are querying, there is no way to request more transactions.

This issue also refers to the legacy node software and library, which are no longer maintained.
