### ISSUE TITLE
No command to set up the proxy (using nodejs)

### ISSUE THREAD

**Issue by ThomasBouquet95** [iotaledger/iota.js#72]
Hello everyone. Almost all companies are behind a **proxy**. If we want that IOTA become the backbone of IOT and micro payment we have to allow companies to use it. To set up the proxy do the following : 

_Note that you have to change ec2-user by your user name_ 

So, the IOTA lib is using this https://www.npmjs.com/package/xmlhttprequest to simulate the browser environment. This doesn’t have a proxy configuration, but there is fork that does https://github.com/jbeuckm/node-XMLHttpRequest 

Copy https://github.com/jbeuckm/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js that has the proxy patch to the local file system on /home/ec2-user/IOTA/test/node_modules/xmlhttprequest/lib/xml/XMLHttpRequest.js

The new library needs a config parameter, so we need to change /home/ec2-user/IOTA/test/node_modules/iota.lib.js/lib/utils/makeRequest.js to include the config parameter and pass it to make request:

So at the beginning of the file:

`var config = { "proxy" : { "host": "your proxy", "port" : XXXX}}`

Change everywhere in the file 

`    var request = new XMLHttpRequest();`

by 
`    var request = new XMLHttpRequest(config); `

**Comment by giltotherescue** [comment]
It would also be nice to have a config option to use the native XMLHttpRequest instead of the imported library. I am working on a hybrid mobile app, and this is the only limitation preventing me from using iota.lib.js client side. I was able to route around the issue by making a copy of the library and editing it to comment out the import of the XMLHttpRequest library.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
