### ISSUE TITLE
Cannot import @iota/iota.js as ES6 module with native Node

### ISSUE THREAD

**Issue by viossat** [iotaledger/iota.js#772]
## Bug description

Module `@iota/iota.js` with native Node (no Babel/TypeScript etc) can only be imported with `require()`, `import` returns an error.

## Version

Package: 1.8.4
Node: from 12 to 17

## Steps To reproduce the bug

1. `package.json`
```json
{
  "type": "module",
  "dependencies": {
    "@iota/iota.js": "^1.8.4"
  }
}

```
2. `index.js`
```js
import { SingleNodeClient } from '@iota/iota.js'

const client = new SingleNodeClient('anything')
```
3. run `node index.js`

## Errors

```
file:///PROJECT/node_modules/@iota/iota.js/dist/esm/polyfill-node.mjs:7
    globalThis.fetch = require("node-fetch");
    ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'PROJECT/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by obany** [comment]
Thank for the report, didn't spot this before as the module solutions I had using iota.js had already polyfilled node-fetch before loading iota.js, anyway the 1.8.5 release should fix this.
