### ISSUE TITLE
Tags are ignored by lib

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iota.js#90]
when moving `tag` to `obsoleteTag`, 
the lib no longer copies the tag provided to transaction - in `prepareTransfers` : [api.js#L1003](https://github.com/iotaledger/iota.lib.js/blob/master/lib/api/api.js#L1003)

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
