### ISSUE TITLE
Problem with integration of iota.lib.js into other npm module.

### ISSUE THREAD

**Issue by Isarstyle** [iotaledger/iota.js#93]
Getting the following error when importing the iota.lib.js into another npm module

```
These dependencies were not found:

* child_process in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js
* fs in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js

```

Reproduction: 
create new npm module --> var IOTA = require('iota.lib.js') --> npm install new npm module into quasar emtpy project --> error from above.

**Comment by lsquires** [comment]
I had this problem too, the problem for me was webpack trying to build it with fs and child_process which don't run in the browser. To fix it I added
`externals: [{
    xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
  }],`
to the module.exports of my webpack config

**Comment by java99** [comment]
Thanks! working perfectly when using webpack 
+1

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
